[features]
seeds = false
[programs.localnet]
solch_staking = "2syTJgihH8pYYnjKK4ZfMacrtzUSd6iTY4pHcC2FrnRZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/panda/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
